site_name: Predictive Maintenance AI
site_description: End-to-end ML/DL pipeline for predicting industrial equipment failures
site_author: Jose Herrera
repo_url: https://github.com/joseherrera1988/predictive-maintenance-system
repo_name: joseherrera1988/predictive-maintenance-system

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md
  - Architecture Diagrams: architecture.md
